### PR TITLE
Fail reading name DB while in initial download.

### PR DESCRIPTION
**Pull request by domob1812**
Fail `name_show`, `name_history`, `name_scan` and `name_filter` while the client is in the initial blockchain download.  This fixes https://github.com/namecoin/namecore/issues/2.

No need to merge this, if I get an ACK I'll push the code myself.

### CODE REVIEW

**Comment by domob1812** [comment]
Any news here?  If I don't get an NAK by the weekend, I will push the commit.  (Note that it is just a single commit and that it passes Travis-CI.  Not sure why Github got confused.)

**Comment by JeremyRand** [comment]
I haven't had time to test, but if no one gets to it by the weekend, I have no objection to merging.

**Comment by JeremyRand** [comment]
I attempted to build this PR with Gitian; the resulting binary segfaults immediately when I run it (x64 version, on Fedora 21).  I suspect this is an issue on my end, and is probably not relevant to this PR.  In any event, I will be unable to test this until I figure out what's wrong with my setup (which will probably take quite a while).

**Comment by domob1812** [comment]
Pushed.

**Pull request closed without merging**
