### PR TITLE
Namecoin Core Qt Rebrand

### PR DESCRIPTION
**Pull request by fsb4000**
More info: https://forum.namecoin.info/viewtopic.php?f=18&t=2312

### CODE REVIEW

**Comment by domob1812** [comment]
Looks good to me.  Can you please just squash both commits?  I would prefer it that way (but if you can't, that's also fine).  ACK.  I would also like to get another ACK and quick test / review, @phelixbtc, @cassiniNMC, @JeremyRand?

**Comment by JeremyRand** [comment]
I'm unable to quickly test (my Gitian setup is temporarily broken, and I can't easily build without Gitian on Fedora due to OpenSSL issues).  @domob1812 , did you test it on Debian?  If so, it would probably be better to have @phelixbtc or @cassiniNMC test, since they can test Windows or OS X.

**Comment by domob1812** [comment]
No, I didn't test (I'm officially on vacation currently and don't have too much time to spend on Namecoin at the moment).  I think it should be fine to test on just one platform, as the changes are just strings and new graphics - thus I'm hoping for an ACK from phelix or cassini, since they have tested it already IMHO.  But if you can, it would be good to get testing results from you on GNU/Linux as well.

**Comment by JeremyRand** [comment]
Okay.  I'll see if I can get my Gitian setup fixed soon, but I wouldn't expect it.  Hopefully Phelix or Cassini can do it faster.

**Comment by fsb4000** [comment]
@domob1812:
>Can you please just squash both commits?

done

**Comment by domob1812** [comment]
Thanks, merging.

**Pull request merged**
